name: Weekly Music Suggestions

on:
  schedule:
    - cron: "0 5 * * MON" # 05:00 UTC every Monday
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install python-dotenv requests

      - name: Run script
        env:
          LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
          LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
        run: python script.py

      - name: Commit results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add "suggestions/*.txt"
          git commit -m "Weekly suggestions"
          git push
